### ISSUE TITLE
【Android/iOS】-【最新版】安卓提示未知协议webrtc？

### ISSUE THREAD

**Issue by tion126** [tencentyun/MLVBSDK#142]
【当前现象】
unknown protocol: webrtc iOS貌似没这问题

【集成包】
基础版Smart

【流id或url】 1234_test

【问题时间段】
2019-09-01 16:23~16:55

【机型】如iPhone 7 Plus

【之前版本有无此问题】
如6.4之前没有，6.6有

【复现概率】
必现 / 偶现(如有大约概率请标明)

【复现途径】
W/System.err: java.net.MalformedURLException: unknown protocol: webrtc
W/System.err:     at java.net.URL.<init>(URL.java:608)
W/System.err:     at java.net.URL.<init>(URL.java:498)
W/System.err:     at java.net.URL.<init>(URL.java:447)
W/System.err:     at com.tencent.liteav.network.TXCFLVDownloader.connect(TXCFLVDownloader.java:431)
W/System.err:     at com.tencent.liteav.network.TXCFLVDownloader.processMsgConnect(TXCFLVDownloader.java:142)
W/System.err:     at com.tencent.liteav.network.TXCFLVDownloader.reconnect(TXCFLVDownloader.java:376)
D/TraeAudioManager: [W]connect speakerPhone: do nothing
W/System.err:     at com.tencent.liteav.network.TXCFLVDownloader.processMsgReconnect(TXCFLVDownloader.java:314)
W/System.err:     at com.tencent.liteav.network.TXCFLVDownloader.access$300(TXCFLVDownloader.java:36)

**Comment by Tencent-Alice** [comment]
您好 请问这个问题是偶发还是必现？其他机型有这个case吗  有具体报错截图吗技术问题 欢迎交流 Q2562367495 注明来意
