### ISSUE TITLE
【Android】-【6.8.7969】【问题简述，ANR】

### ISSUE THREAD

**Issue by droidsde** [tencentyun/MLVBSDK#52]
【当前现象】
使用过程中程序不响应，出现ANR

【集成包】
专业版Professional

【流id或url】 

【问题时间段】
2019-09-01 16:23~16:55

【机型】如Android 4.4定制系统

【之前版本有无此问题】

【复现概率】
必现 

【复现途径】

【Demo 复现途径】
可复现 
1.直接使用摄像头推流

【相关附件】
----- pid 6905 at 2019-12-19 19:42:12 -----
Cmd line: com.tencent.liteav.demo

JNI: CheckJNI is off; workarounds are off; pins=2; globals=352 (plus 5 weak)

DALVIK THREADS:
(mutexes: tll=0 tsl=0 tscl=0 ghl=0)

"main" prio=5 tid=1 WAIT
  | group="main" sCount=1 dsCount=0 obj=0x4163bca8 self=0x41574580
  | sysTid=6905 nice=0 sched=0/0 cgrp=apps handle=1074823508
  | state=S schedstat=( 0 0 0 ) utm=1203 stm=217 core=2
  at java.lang.Object.wait(Native Method)
  - waiting on <0x419a83a8> (a com.tencent.liteav.renderer.TXCGLSurfaceViewBase$j)
  at java.lang.Object.wait(Object.java:364)
  at com.tencent.liteav.renderer.TXCGLSurfaceViewBase$i.f(TXCGLSurfaceViewBase.java:639)
  at com.tencent.liteav.renderer.TXCGLSurfaceViewBase.surfaceDestroyed(TXCGLSurfaceViewBase.java:174)
  at android.view.SurfaceView.updateWindow(SurfaceView.java:556)
  at android.view.SurfaceView.setVisibility(SurfaceView.java:250)
  at com.tencent.rtmp.ui.TXCloudVideoView.stop(TXCloudVideoView.java:374)
  at com.tencent.liteav.c.a(TXCCaptureAndEnc.java:552)
  at com.tencent.rtmp.b.b(TXLivePusherImpl.java:191)
  at com.tencent.rtmp.TXLivePusher.stopCameraPreview(TXLivePusher.java:113)
  at com.tencent.liteav.demo.lvb.camerapush.CameraPusherActivity.stopRTMPPush(CameraPusherActivity.java:868)
  at com.tencent.liteav.demo.lvb.camerapush.CameraPusherActivity.access$200(CameraPusherActivity.java:111)
  at com.tencent.liteav.demo.lvb.camerapush.CameraPusherActivity$1.onClick(CameraPusherActivity.java:237)
  at android.view.View.performClick(View.java:4445)
  at android.view.View$PerformClick.run(View.java:18429)
  at android.os.Handler.handleCallback(Handler.java:733)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:136)
  at android.app.ActivityThread.main(ActivityThread.java:5001)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:736)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:570)
  at dalvik.system.NativeStart.main(Native Method)

**Comment by whalehe** [comment]
您好，可以更新到我们最新版本7.2试试，看看有无此问题
