### ISSUE TITLE
【Android】-【6.8.8003】【TXLivePusher.setConfig造成anr，偶发】

### ISSUE THREAD

**Issue by VincentJin-91** [tencentyun/MLVBSDK#78]
【当前现象】
android应用anr，TXLivePusher.setConfig卡死

【集成包】
基础版Smart

【流id或url】 N/A

【机型】Xiaomi Redmi 5A

【复现概率】
偶现，但是频率不是很低

【相关附件】
"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 obj=0x74207560 self=0xe9e84400
  | sysTid=16370 nice=-10 cgrp=default sched=0/0 handle=0xecb54538
  | state=S schedstat=( 296021701676 31168631195 367125 ) utm=25076 stm=4526 core=0 HZ=100
  | stack=0xff59b000-0xff59d000 stackSize=8MB
  | held mutexes=
  kernel: __switch_to+0x70/0x7c
  kernel: futex_wait_queue_me+0xe4/0x144
  kernel: futex_wait+0xfc/0x208
  kernel: do_futex+0xdc/0x8a4
  kernel: compat_SyS_futex+0xdc/0x168
  kernel: el0_svc_naked+0x24/0x28
  native: #00 pc 000174f4  /system/lib/libc.so (syscall+28)
  native: #01 pc 000475cd  /system/lib/libc.so (_ZL33__pthread_mutex_lock_with_timeoutP24pthread_mutex_internal_tbPK8timespec+520)
  native: #02 pc 00035ebd  /data/app/com.sdbean.werewolf.jp-1/lib/arm/libtraeimp-rtmp.so (???)
  native: #03 pc 0001d93f  /data/app/com.sdbean.werewolf.jp-1/lib/arm/libtraeimp-rtmp.so (???)
  native: #04 pc 000769b9  /data/app/com.sdbean.werewolf.jp-1/lib/arm/libliteavsdk.so (???)
  native: #05 pc 001e239d  /data/app/com.sdbean.werewolf.jp-1/oat/arm/base.odex (Java_com_tencent_liteav_audio_impl_TXCTraeJNI_nativeSetTraeANS__ZI+80)
  at com.tencent.liteav.audio.impl.TXCTraeJNI.nativeSetTraeANS(Native method)
  at com.tencent.liteav.audio.impl.a.enableSoftANS(TXCAudioEngImplTRAE.java:119)
  at com.tencent.liteav.audio.a.a(TXCAudioEngine.java:190)
  at com.tencent.rtmp.b.N(TXLivePusherImpl.java:1649)
  at com.tencent.rtmp.b.a(TXLivePusherImpl.java:142)
  at com.tencent.rtmp.TXLivePusher.setConfig(TXLivePusher.java:65)
  at com.sdbean.werewolf.viewmodel.video.PushDao.initPush(PushDao.java:172)
  at com.sdbean.werewolf.viewmodel.video.PushDao.initPushDao(PushDao.java:367)
  at com.sdbean.werewolf.view.PlayActivity.initStream(PlayActivity.java:861)
  at com.sdbean.werewolf.view.PlayActivity.initGame(PlayActivity.java:507)
  at com.sdbean.werewolf.viewmodel.PlayVM.getSocketResponse(PlayVM.java:1652)
  at com.sdbean.werewolf.view.PlayActivity$1.handleMessage(PlayActivity.java:158)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:163)
  at android.app.ActivityThread.main(ActivityThread.java:6239)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
