### ISSUE TITLE
Android自动加载（aar）集成运行报错

### ISSUE THREAD

**Issue by steven945** [tencentyun/MLVBSDK#81]
java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport() (tried Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport and Java_com_tencent_liteav_basic_datareport_TXCDRApi_nativeInitDataReport__)
        at com.tencent.liteav.basic.datareport.TXCDRApi.nativeInitDataReport(Native Method)
        at com.tencent.liteav.basic.datareport.TXCDRApi.<clinit>(TXCDRApi.java:393)
        at com.tencent.liteav.basic.datareport.TXCDRApi.txReportDAU(TXCDRApi.java:80)
        at com.tencent.liteav.basic.b.e.a(LicenceCheck.java:646)
        at com.tencent.liteav.basic.b.e.a(LicenceCheck.java:555)
        at com.tencent.liteav.basic.b.e.d(LicenceCheck.java:486)
        at com.tencent.liteav.basic.b.e.b(LicenceCheck.java:51)
        at com.tencent.liteav.basic.b.e$1.a(LicenceCheck.java:219)
        at com.tencent.liteav.basic.b.c.run(HttpFileUtil.java:127)
        at java.lang.Thread.run(Thread.java:784)

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，建议使用JCenter方式集成，也可以用本地AAR包集成，如果还有问题，烦请附上日志或者截图信息。
