### ISSUE TITLE
安卓进入不开播的直播间崩溃

### ISSUE THREAD

**Issue by JQHee** [tencentyun/MLVBSDK#9]
2019-05-28 12:50:11.196 3324-4258/? W/System.err: java.io.EOFException
2019-05-28 12:50:11.196 3324-4258/? W/System.err:     at java.io.DataInputStream.readFully(DataInputStream.java:200)
2019-05-28 12:50:11.196 3324-4258/? W/System.err:     at java.io.DataInputStream.readInt(DataInputStream.java:389)
2019-05-28 12:50:11.196 3324-4258/? W/System.err:     at com.tencent.qqprotect.qsec.QSecCbMgr.a(ProGuard:127)
2019-05-28 12:50:11.196 3324-4258/? W/System.err:     at com.tencent.qqprotect.qsec.QSecCbMgr.a(ProGuard:110)
2019-05-28 12:50:11.196 3324-4258/? W/System.err:     at com.tencent.qqprotect.qsec.QSecCbMgr.<init>(ProGuard:99)
2019-05-28 12:50:11.196 3324-4258/? W/System.err:     at com.tencent.qqprotect.qsec.QSecFramework.<init>(ProGuard:125)
2019-05-28 12:50:11.196 3324-4258/? W/System.err:     at com.tencent.qqprotect.qsec.QSecFramework.a(ProGuard:164)
2019-05-28 12:50:11.196 3324-4258/? W/System.err:     at com.tencent.mobileqq.app.automator.step.StartQSecLogic.a(ProGuard:15)
2019-05-28 12:50:11.196 3324-4258/? W/System.err:     at com.tencent.mobileqq.app.automator.AsyncStep.run(ProGuard:50)
2019-05-28 12:50:11.196 3324-4258/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2019-05-28 12:50:11.196 3324-4258/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2019-05-28 12:50:11.196 3324-4258/? W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by vintHua** [comment]
这个crash堆栈不是这个项目的
